#!/usr/bin/perl

use lib '/home/wicker/data/WICKERsoft/';
use Biomodule;
use GD;

if (@ARGV < 4) {
	print "1. = query for blast outputs\n";
	print "2. = min len\n";
	print "3. = min sim\n";
	print "4. = x-zoom (bp/pixel, e.g. 20)\n";
	exit;
	}


$infile = $ARGV[0];
$min_len = $ARGV[1];
$min_sim = $ARGV[2];
$x_zoom = $ARGV[3];

$dot_zoom = 100;


$flank = 5000;
$chr_dist = 30;

$log = "log_TE_fam_cvg_insertions_$ARGV[0]";
open(LOG,">$log");
print LOG "inseq\tfamily\tlen\tlen_fam\thit\tcvg\trem\tflag\thit_num\tori\n";


foreach $infile (<*$ARGV[0]*.blast*>) {

	print "\nprocess $infile ---------------------\n\n";
	&process;
	}

print "wrote $log\n";




# main sub to process blast +++++++++++++++++++++++++++++++++++++++++++
sub process {

$out = "$infile\_blast_dot.png";


# get length and name of inseq
open(IN,"$infile");
LEN:while(<IN>) {
        ($l) = /^Query=\s+(\S+)/;
        if ($l) {
                $inseq = $l;
                }

	($l) = /^Length=(\S+)/;
	if ($l) {
		$len = $l;
		last(LEN);
		}
	}	
close(IN);
print "$inseq\t$len bp\n";

# make overall coverage array to avoid redundant hits from multiple families
@tot_cvg = ();
for($i=0;$i<$len;$i++) {
	$tot_cvg[$i] =0;
	}


# collect data from blast output in 2D array
(@test) = &parse_blast($infile);
$count_hit =0;
@hit = ();
$count_fam = 0;
@fam = ();

# loop over all hits +++++++++++++++++++++++++++
BLAST: foreach $test (@test) {

($ID,$rem,$s_size) = ($test =~ /ID=([^;]+);([^;]+);(\d+)/);
(@data) = ($test =~ /^(data=.+)$/gm);


# create family name, exclude species	
# ... to only allow each family once
($code,$fa) = ($ID =~ /^([^_]+)_[^_]+_([^_]+)/);
$fam = "$code\_$fa";


# only process hits if family occurs for the first time 
unless ($fam ~~ @fam) {

push(@fam,$fam);
$len_fam{$fam} = $s_size;
$count_fam ++;

print "NEW\t$count_fam\t$fam\t $s_size\n";

# loop over all alignments ++++++++++++++ 
foreach $data (@data) {

($Eval,$sim,$be1,$en1,$be2,$en2,$seq1,$seq2) = ($data =~
/data=[^;]+;([^;]+);([^;]+);([^;]+);([^;]+);([^;]+);([^;]+);([^;]+);([^;]+)/);

$diff = abs($be1-$en1);

# if criteria are met, make output
if (($diff >= $min_len)&&($sim >=$min_sim)) {

	$ori = "for";
	$beg = $be1;
	$end = $en1;
	if ($be2 > $en2) {
		$ori = "rev";
		} 

	$flag = 1;	
	$hit[$count_hit][0] = $be1;
	$hit[$count_hit][1] = $en1;
	$hit[$count_hit][2] = $be2;
        $hit[$count_hit][3] = $en2;
	$hit[$count_hit][4] = $sim;
	$hit[$count_hit][5] = $fam;
	$hit[$count_hit][6] = $s_size;
	$hit[$count_hit][7] = $ori;
	$hit[$count_hit][8] = $flag;
	$count_hit++;

	print "$inseq\t$fam\t$be1\t$en1\n";

	}
}
} # end check family


}


print "blast hits:\t$count_hit\n";
print "families:\t$count_fam\n";


# calc cvg of query with all families
$insertion_yes = 0; 
foreach $fam (@fam) {

	$len_fam = $len_fam{$fam};

	# initita cvg array for family
	@cvg = ();
	for($i=0;$i<$len;$i++) {
		$cvg[$i] = 0;
		}

	# collect cvg for all hits for family	
	for($i=0;$i<$count_hit;$i++) {
		if ($hit[$i][5] eq $fam) {

			$be1 = $hit[$i][0];
			$en1 = $hit[$i][1];
			for($c=$be1;$c<$en1;$c++) {
				# exclude previously covered regions
				if ($tot_cvg[$c] == 0) {
					$cvg[$c]++;
					$tot_cvg[$c]++;
					}
				}
			$ori = $hit[$i][7];	
			print "$fam\t$be1\t$en1\t$ori\n";	
			}
		}

	# calc portion covered by family
	$cvg = 0;
	for($i=0;$i<$len;$i++) {
		if ($cvg[$i] > 0) {
			$cvg++;
			}
		}

	$rel = sprintf("%.02f",($cvg/$len*100));	
	$cvg_fam{$fam} = $rel;
	$bp_fam{$fam} = $cvg;

	# determine if inseq correspond to frament or full insertion
	# ... if inseq len ~= family length, classify as insertion
	$rem = "frag";
	$delta = abs($len_fam-$len);
	if (($delta < 350) && ($rel > 95)) {
		$rem = "ins";
		$insertion_yes = 1;
		}
	print "$fam\t$len_fam\t$cvg\t$rel%\t==> $rem ****\n";
	$rem{$fam} = $rem;
	$ori{$fam} = $ori;

	}





# if one family was classified as full-length insertion, flag all hits for the output file
&flag_all;

sub flag_all {
for($i=0;$i<$count_hit;$i++) {
	$hit[$i][8] = 0;
	}
}


# make image +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# calculate x-zoom factor and image height
$wide = int(($len+2*$flank)/$x_zoom)+int($len/$dot_zoom);
$high = $count_hit*$chr_dist+$count_fam*$chr_dist*2;

$x_base = 150;
$y_base = 50;

# base for dot plot
$x_base2 = $x_base + int(($len+2*$flank)/$x_zoom);

print "$wide x $high\n";

# create a new image
$img_x = $wide +$x_base+100;
$img_y = $high +2*$y_base;
$img = new GD::Image($img_x,$img_y);

# allocate some colors
$white = $img->colorAllocate(255,255,255);
$black = $img->colorAllocate(0,0,0);
$red = $img->colorAllocate(255,0,0);
$blue = $img->colorAllocate(0,0,255);
$gray = $img->colorAllocate(150,150,150);

# draw x scale
$step = 1000;
for($i=0;$i<=$len;$i+=$step) {
        $x1 = $x_base+int(($flank+$i)/$x_zoom);
        $y1 = $y_base;
        $y2 = $y1+3;
        $img->line($x1,$y1,$x1,$y2,$black);
        $img->string(gdSmallFont,$x1,$y2-18,$i,$black);
        }


# title
$x = $x_base+int($flank/$x_zoom);
$y = 10;
$label = "$inseq ($len bp)";
$img->string(gdLargeFont,$x,$y,$label,$black);

# display blast hits
$ID_old = "dummy";
$y_hit = 0;
for($i=0;$i<$count_hit;$i++) {

	$be1 = $hit[$i][0];
	$en1 = $hit[$i][1];
	$be2 = $hit[$i][2];
        $en2 = $hit[$i][3];
	$sim = $hit[$i][4];
	$ID = $hit[$i][5];
	$len2 = $hit[$i][6];
	$ori = $hit[$i][7];

	$cvg = $cvg_fam{$ID};
	$rem = $rem{$ID};

	# label for new hit 
	if ($ID ne $ID_old) {
		$y_hit += 2*$chr_dist;
		$y1 = $y_base+$y_hit;
		$x1 = 10;

		$lab = "$ID ($len2 bp)";
		$lab2 = "$cvg% $rem";
		
		$img->string(gdSmallFont,$x1,$y1,$lab,$black);
		$img->string(gdSmallFont,$x1,$y1+15,$lab2,$black);

		$ID_old = $ID;

		# make box for dot plot
		$x1 = $x_base2;
		$x2 = $x_base2+int($len/$dot_zoom);
		$y_box1 = $y_base+$y_hit;
		$y_box2 = $y1+int($len2/$dot_zoom);
		$fill = $black;		
		$img->rectangle($x1,$y_box1,$x2,$y_box2,$fill);
		}

	# show hit on query
	$x1 = $x_base + int(($be1+$flank)/$x_zoom);
	$x2 = $x_base + int(($en1+$flank)/$x_zoom);

	$y1 = $y_base+$y_hit;

	#print "$ID\t$be1\t$en1\t$be2\t$en2\tlen2=$len2\t$sim%\t$ori\t$x1\t$x2\t$y1\n";

	$fill = $red;
	$img->filledRectangle($x1,$y1,$x2,$y1+2,$fill);

	# show hit on subject
	$rem = $ori;
	if ($ori eq '+') {
		# make gray line for whole element
		$x1 = $x_base+int(($be1-$be2+$flank)/$x_zoom);
		$x2 = $x_base+int(($be1-$be2+$len2+$flank)/$x_zoom);

		}

	if ($ori eq '-') {
                # make gray line for whole element
                $x1 = $x_base+int(($be1-$len2+$be2+$flank)/$x_zoom);
                $x2 = $x_base+int(($be1-$len2+$be2+$len2+$flank)/$x_zoom);

                }

	if ($x1 < $x_base) {
		$x1 = $x_base;
		$rem .= " /";
		}
	if ($x2 > $x_base2-20) {
                $x2 = $x_base2-20;
                }	
	$y1 = $y_base+$y_hit+5;	

	$fill = $gray;
        $img->filledRectangle($x1,$y1,$x2,$y1+2,$fill);	
	# make ori label
	$img->string(gdSmallFont,$x1-20,$y1-5,$rem,$black);


	$y_hit+=$chr_dist;

	# show it on subject 

	# make mini dot plot at the side
	$x1 = $x_base2+ int($be1/$dot_zoom);
	$x2 = $x_base2+ int($en1/$dot_zoom);
	$y1 = $y_box1+ int($be2/$dot_zoom);
        $y2 = $y_box1+ int($en2/$dot_zoom);
	$img->line($x1,$y1,$x2,$y2,$black);


	}


# convert into png data
#$out = "GC_plot_$ARGV[0]\.png";
open $png, '>', $out or die;
binmode $png;
print $png $img->png;


# open image
print "opening image, please wait\n";

`eog $out`;

print "wrote $out\n";

print "classification ok?\n";
chomp ($reply = <STDIN>);
if ($reply eq 'n') { 
	$insertion_yes = 1;
	}

# write output 
$count_log = 0;
foreach $fam (@fam) {
	$len2 = $len_fam{$fam};
	$cvg = $cvg_fam{$fam};
	$rem = $rem{$fam};
	$bp_fam = $bp_fam{$fam};
	$ori = $ori{$fam};

	if ($bp_fam > 0) {
		$count_log++;
		print "LOG\t$inseq\t$fam\t$len\t$len2\t$bp_fam\t$cvg%\t$rem\t$insertion_yes\t$count_log\t$ori\n";
		print LOG "$inseq\t$fam\t$len\t$len2\t$bp_fam\t$cvg%\t$rem\t$insertion_yes\t$count_log\t$ori\n";
		}



	}

}

















